
[build]
target = "target-sys/x86_64.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
runner = "bootimage runner"